### ISSUE TITLE
Skosmos interface is down

### ISSUE THREAD

**Issue by peetmate** [gacs/gacs-scheme#11]
Hello,

we are  the middle of tagging the Evidence for Resilient Agriculture database with GACS concepts, but the [website ](http://browser.agrisemantics.org/gacs/en/) seems to be down. Colleagues from all over the world are experiencing the same issue.

![image](https://user-images.githubusercontent.com/20173624/86213410-584ff880-bb82-11ea-9537-70d8b72b7648.png)

Are you able to indicate when the service will be available again?

Many thanks,

Pete Steward

**Comment by semantic-nomad** [comment]
Hmm...I'm looking into this.

**Comment by semantic-nomad** [comment]
This issue appears to have been resolved.
