### ISSUE TITLE
Create a bibliography page for GACS publications

### ISSUE THREAD

**Issue by semantic-nomad** [gacs/gacs-scheme#2]
No need to be stingy, put all info with links on the page.

**Comment by tombaker** [comment]
On Tue, Mar 19, 2019 at 03:16:43PM +0000, brandon wrote:
> No need to be stingy, put all info with links on the page.

If there are any new GACS pages that I can point people to, 
please let me know before Sunday (which is when the scientific 
part of the conference starts).

Also, I can check the links against my own set of bookmarks.

**Comment by tombaker** [comment]
Some the following materials should perhaps be re-published in a GACS repo.

The first set of reports, from November 2014:

* https://github.com/tombaker/gacswg/blob/master/GACS_Status_Quo_1.0.pdf
* https://github.com/tombaker/gacswg/blob/master/Recommended_Improvements_1.0.pdf
* https://github.com/tombaker/gacswg/blob/master/GACS_Integration_Proposal_1.0.pdf

The July 2015 workshop on Agrisemantics:

* http://aims.fao.org/agrisemantics-workshop-2015
* http://s3-eu-west-1.amazonaws.com/assets.aims.fao.org/public/Report_workshop_Agrisemantics.pdf
* http://s3-eu-west-1.amazonaws.com/assets.aims.fao.org/public/Agrisemantics_participants.pdf

Some Powerpoint presentations about GACS from 2016:

* https://github.com/tombaker/gacswg/blob/master/presentations/2016-10-13.gacs-dc2016.pdf 
* https://github.com/tombaker/gacswg/blob/master/presentations/2016-11-07.gacs-icfoods.pdf

Paper about GACS for MTSR, November 2016:

* https://github.com/agrisemantics/2016_11_goettingen/blob/master/mtsr_paper/2016-11-25.gacs-mtsr-paper.pdf

The Goettingen workshop reports (the second is a shorter version of the first):

* https://github.com/agrisemantics/2016_11_goettingen/blob/master/gacs_workshop_report.pdf
* https://github.com/agrisemantics/2016_11_goettingen/blob/master/gacs_workshop_summary.pdf (shorter)

Presentation of the results of the Quality Improvement Project (QIP), December 2017:

* https://github.com/agrisemantics/gacs-qip/blob/master/presentations/2017-12-05.gacs_qip_report.pdf

The documentation website from QIP, which could continue to evolve as the maintenance handbook for GACS:

* https://agrisemantics.github.io/gacs-qip/

A March 2018 concept paper discussed in Berlin:

* https://github.com/agrisemantics/2018_02_berlin/blob/master/gacs_vision/gacs_concept.pdf

**Comment by semantic-nomad** [comment]
This may be better served on the Agrisemantics web space.

**Comment by semantic-nomad** [comment]
I now have a GACS_outputs.bib file we can use.  It's missing some info but it's a start.

**Comment by semantic-nomad** [comment]
see [README](https://github.com/gacs/gacs-scheme/blob/master/README.md) for first draft.

**Comment by semantic-nomad** [comment]
I'll create a page on the agrisemantics.org/gacs area for these.

**Comment by semantic-nomad** [comment]
These have been added to https://agrisemantics.org/GACS/

**Comment by saubin78** [comment]
Good but there are no links. Most of the references are not accessible :(
